Refactor/interfaces 2
morpho-org/metamorpho pull request #272
Opened 2023-10-25 15:48 UTC by QGarchery

Duplicate of https://github.com/morpho-org/metamorpho/pull/240 that was permaturely merged

2023-10-25 16:08 UTC, MerlinEgalite approved these changes

2023-10-26 07:42 UTC, Rubilmax approved these changes

2023-10-26 10:15 UTC, MerlinEgalite requested changes

2023-10-26 11:58 UTC, Rubilmax commented on src/interfaces/IMetaMorpho.sol
> +/// @dev Use this interface for MetaMorpho vaults to have access to all the functions with the appropriate signatures.
I think it's ok in this context because we mention function right before, but I'm not against if you feel more comfortable

2023-10-26 15:37 UTC, Rubilmax approved these changes

2023-10-26 19:00 UTC, MerlinEgalite approved these changes

2023-11-07 16:04 UTC, QGarchery commented
closing in favor of #311

2023-11-07 16:04 UTC, closed without merging