Check duplicates in supply queue 109
morpho-org/metamorpho pull request #284
Opened 2023-11-01 13:23 UTC by MerlinEgalite

Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/109

2023-11-02 09:29 UTC, Rubilmax requested changes

2023-11-02 09:29 UTC, Rubilmax commented on src/MetaMorpho.sol
> +                if (Id.unwrap(newSupplyQueue[i]) == Id.unwrap(newSupplyQueue[j])) {
`newSupplyQueue[i]` can be stored onto the stack

2023-11-02 09:29 UTC, Rubilmax commented on test/metamorpho_tests.tree
> +            ├── when some markets are duplicated
```suggestion
            ├── when there is at least a duplicate market
```

2023-11-02 09:29 UTC, Rubilmax commented on test/metamorpho_tests.tree
> +            └── when all the markets of newSupplyQueue have non zero cap and are not duplicated
```suggestion
            └── when all the markets of newSupplyQueue have non zero cap and are unique
```

2023-11-02 09:34 UTC, Rubilmax commented
For reference: the nested loop costs 3k in the case of a 5 markets supply queue

2023-11-02 10:41 UTC, Jean-Grimal approved these changes

2023-11-02 13:07 UTC, Rubilmax approved these changes
The implementation works, but it costs a lot

2023-11-02 13:07 UTC, Rubilmax commented on src/MetaMorpho.sol
> +                }
```suggestion
                if (Id.unwrap(id) == Id.unwrap(newSupplyQueue[j])) revert ErrorsLib.DuplicateMarket(id);
```

2023-11-02 13:11 UTC, Rubilmax requested changes
Here's my reasoning: https://github.com/cantinasec/review-morpho-blue-1/issues/109#issuecomment-1790698623

2023-11-02 13:12 UTC, MerlinEgalite commented on src/MetaMorpho.sol
> +                }
Indeed the compiled does not complain

2023-11-02 14:22 UTC, MerlinEgalite commented
> For reference: the nested loop costs 3k (5%) in the case of a 5 markets supply queue and 116k (60%) in the case of a 30 markets supply queue

3k is ok.

I agree that 116k is a lot but I'm not sure we this function we'll be trigger several times a day tbh

2023-11-06 08:43 UTC, MerlinEgalite commented
We acknowledge this issue because:
- The gas cost is important
- The the curator can fix a rogue allocator by disabling the allocator and setting a new supply queue

2023-11-06 08:43 UTC, closed without merging