Fix typos
morpho-org/metamorpho pull request #425
Opened 2024-07-18 14:41 UTC by cratiu222

Hello
I found some minor typos in your docs.
Br, Christina.

2024-07-18 16:48 UTC, MathisGD requested changes
thx

2024-07-18 16:48 UTC, MathisGD commented on certora/specs/Reentrancy.spec
> -// Check that there are no untrusted external calls, ensuring notably reentrancy safety.
here the meaning is changed, please roll back

2024-07-18 16:48 UTC, MathisGD commented on certora/specs/Enabled.spec
> -    // Safe require because j is not otherwise constrained.
same here

2024-07-18 17:39 UTC, cratiu222 commented
done, sir

2024-07-19 22:59 UTC, MathisGD requested changes

2024-07-19 22:59 UTC, MathisGD commented on certora/specs/Enabled.spec
> +    // Safe is require because j is not otherwise constrained.
```suggestion
    // Safe require because j is not otherwise constrained.
```

We want to say that the "require" is safe

2024-07-20 07:55 UTC, MathisGD approved these changes

2024-07-21 14:38 UTC, QGarchery approved these changes

2024-07-21 16:27 UTC, merged